# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scripts/read_ranobe.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(733, 559)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -1119, 681, 1720))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.last_btn = QtWidgets.QPushButton(self.widget_2)
        self.last_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.last_btn.setObjectName("last_btn")
        self.horizontalLayout.addWidget(self.last_btn)
        self.next_btn = QtWidgets.QPushButton(self.widget_2)
        self.next_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.next_btn.setObjectName("next_btn")
        self.horizontalLayout.addWidget(self.next_btn)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.last_btn2 = QtWidgets.QPushButton(self.widget_4)
        self.last_btn2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.last_btn2.setObjectName("last_btn2")
        self.horizontalLayout_3.addWidget(self.last_btn2)
        self.next_btn2 = QtWidgets.QPushButton(self.widget_4)
        self.next_btn2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.next_btn2.setObjectName("next_btn2")
        self.horizontalLayout_3.addWidget(self.next_btn2)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.widget_5)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_5.addWidget(self.plainTextEdit)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_5.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_5.addWidget(self.pushButton_5, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_3.addWidget(self.widget_5)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.last_btn.setText(_translate("MainWindow", "<<<"))
        self.next_btn.setText(_translate("MainWindow", ">>>"))
        self.label.setText(_translate("MainWindow", "ничего не понял. Теперь за лечение мамы, Киму нужно было платить в среднем от трех до четырех миллионов вон каждый месяц.\n"
"\n"
"У Хен-Ву были родственники со стороны матери и стороны отца, дяди пришли впятером и вручили конверт с деньгами растерянному мальчику.\n"
"\n"
"— Это конечно может показаться очень жестоким, но большего сделать для лечения твоей матери мы не можем.\n"
"\n"
"Больше он этих людей не видел, Ким чувствовал себя просто ужасно. Он сложил все деньги, которые у него были и получил около трех миллионов вон, но этого было не достаточно, чтобы оплатить хотя бы больничный счёт на месяц. А ведь Хен-Ву еще надо было на что-то жить. В первый раз в жизни юноша осознал и понял, как тяжело доставались деньги его родителям, которые Ким тратил на все те вещи, которые хотел получить. Времени вырасти и повзрослеть ему не дали, и юноша перестал быть тем мальчиком, который недавно смотрел телесериалы и переживал за их героев. Столкнувшись с тяжёлой жизненной ситуацией, Ким Хен-Ву изменился.\n"
"\n"
"Его жизнь так же изменилась, и теперь проснувшись на рассвете, юноша разносил газеты и молоко, после чего шёл работать разнорабочим на стройку. Тело очень болело с непривычки, но он продолжал работать, а не отдыхать. Это было не потому, что он стал более серьёзно относиться к жизни, у него просто не было другого выбора. Его заработка едва хватало, чтобы покрывать расходы на проживание и больницу.\n"
"\n"
"Родственники и друзья, которые раньше хвалили отца за щедрость теперь же, когда он умер, а мать нуждалась в дорогостоящем лечении, даже не попытались помочь. А на просьбы одолжить немного денег никак не реагировали. Это было следствием того, что они не думали, что смогут вернуть свои деньги обратно.\n"
"\n"
"Еще до окончания средней школы Ким Хен-Ву столкнулся с безразличием окружающих и осознал то, что теперь ему никто не поможет.\n"
"\n"
"«Я живу только для себя и для того, чтобы заботится о своей маме!»\n"
"\n"
"Чтобы не расстраивать маму он доучился последний год в школе, хотя и хотел уйти из неё. После окончания школы ничего не изменилось, хотя у него и появилось больше времени для работы. Он работал целыми днями, но беспокойство о том, сможет ли он оплатить счета в конце каждого месяца, не покидало его ни на секунду.\n"
"\n"
"Смотря на сверстников, Ким постепенно начал завидовать им. Эти девушки и юноши носили модную одежду и имели новые телефоны последних моделей, но теперь все это ему было недоступно. Смотрел и завидовал тем, кто мог откладывать деньги или просто имел сбережения. Но самую большую зависть Хен-Ву испытывал перед сотрудниками компаний производящих видео-игры, ведь работа в подобной фирме всегда была мечтой мальчика. До трагических событий произошедших в его жизни, он бывало часто играл всю ночь.\n"
"\n"
"Хотя ему и пришлось отказаться от идеи поступить в университет, мечта оставалась мечтой и отказываться от неё он не собирался! Ким ходил на курсы и поэтому платил 300 тысяч вон каждый месяц.\n"
"\n"
"В один из дней к нему подошёл его преподаватель и поинтересовался.\n"
"\n"
"— Хен-Ву, как вы смотрите на то чтобы поработать в компании занимающейся разработкой игр?\n"
"\n"
"— Игровой компании?\n"
"\n"
"— Видите ли, сонбэ сказал мне, что знает одну из таких компаний, и в данный момент она набирает новых сотрудников. Меня попросили порекомендовать нескольких студентов-отличников, и я подумал о вас. Так как вы смотрите на то, чтобы поработать там?\n"
"\n"
"[примечание: сонбэ — обращение к старшему товарищу, коллеге по работе]\n"
"\n"
"— Но нормально ли то, что я не заканчивал университет?\n"
"\n"
"— Там к счастью нет требований к образованию.\n"
"\n"
"— Что это за компания?\n"
"\n"
"— Вы слышали что-нибудь о «Global Exos Korea»?\n"
"\n"
"— Да, слышал."))
        self.last_btn2.setText(_translate("MainWindow", "<<<"))
        self.next_btn2.setText(_translate("MainWindow", ">>>"))
        self.label_2.setText(_translate("MainWindow", "Comments:"))
        self.pushButton_5.setText(_translate("MainWindow", "leave a commet"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
